project:
  type: website
  output-dir: docs

website:
  title: "Fatimah Yunusa "
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: "CV"
        href: pdfs/Resume_3.pdf
      - icon: envelope
        text: "Email"
        href: "mailto:fatimah.yunusa@mail.utoronto.ca"
      - icon: github
        text: "Github"
        href: https://github.com/fatimahsy 
      - text: "About Me"
        href: about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



